# Generated by Django 5.2.1 on 2025-05-17 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name_th', models.CharField(blank=True, max_length=100, null=True)),
                ('sunlight', models.CharField(blank=True, max_length=255, null=True)),
                ('water', models.CharField(blank=True, max_length=255, null=True)),
                ('care_tip', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('payment_method', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plants')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plants.orders')),
            ],
            options={
                'db_table': 'order_items',
                'managed': True,
            },
        ),
    ]
