import { Geist, Geist_Mono,  Prompt ,Montserrat} from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const promptFont = Prompt({
  subsets: ["latin"],
  weight: ["100","200","300","400", "500", "600", "700"],
  variable: "prompt"
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100","200","300","400", "500", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <Navbar />
          <main>{children}</main>
          <Footer />
      </body>
    </html>
  );
}
