import {Montserrat} from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "@/styles/globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100","200","300","400", "500", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={`${montserrat.variable}`}>
      <body>
          <Navbar />
          <main>{children}</main>
          <Footer />
      </body>
    </html>
  );
}
