version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: oxygen-db
    environment:
      POSTGRES_DB: plantdb   
      POSTGRES_USER: opol
      POSTGRES_PASSWORD: opolzaa123 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oxygen-backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=plantdb   
      - DB_USER=opol        
      - DB_PASSWORD=opolzaa123 
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: oxygen-frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres-data:
