services:
  - type: web
    name: plantshop-backend
    env: docker
    repo: https://github.com/creammie888/plant-store
    dockerfilePath: backend/Dockerfile
    # ❌ ลบ buildFilter ทิ้งเพื่อให้เห็นไฟล์ทุกไฟล์
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: plantshop-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: plantshop-db
          property: connectionString

  - type: web
    name: plantshop-frontend
    env: docker
    repo: https://github.com/creammie888/plant-store
    dockerfilePath: frontend/Dockerfile
    # ✅ buildFilter อันนี้ใช้ได้ เพราะอยู่ในโฟลเดอร์ frontend/
    buildFilter:
      paths:
        - frontend/**
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: plantshop-db
    databaseName: plantdb
    user: plantuser
