services:
  - type: web
    name: plantshop-backend
    env: docker
    repo: https://github.com/creammie888/plant-store
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: plantshop-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: plantshop-db
          property: connectionString

  - type: web
    name: plantshop-frontend
    env: docker
    repo: https://github.com/creammie888/plant-store
    dockerfilePath: frontend/Dockerfile
    buildFilter:
      paths:
        - frontend/**
    envVars: []

databases:
  - name: plantshop-db
    databaseName: plantdb
    user: plantuser
